### ISSUE TITLE
tightenco/collect

### ISSUE THREAD

**Issue by winkbrace** [rambler-digital-solutions/hydrogen#6]
Hey, thanks for the nice package. :)

It looks a lot easier for simple stuff (which is 90% of the queries usually). 
Also nice to have the Collection features available for simple result processing. Definitely something to play around with.

Have you considered using https://github.com/tightenco/collect instead of the entire illuminate/support? Or is it meant for Laravel Doctrine projects anyway?

**Comment by SerafimArts** [comment]
@winkbrace inside code, in addition to the `Collections`, [`Arr` and `Str` and other](https://github.com/rambler-digital-solutions/hydrogen/search?l=PHP&q=Illuminate) helpers are used. It seems to me that I can really try to rewrite them... But...

Adding full collections package (`illuminate/support`) I considered 2 things:
1) For people who are already using Laravel, it does not make sense to carry an extra `tightenco/collect` package.
2) For other people, a set of helpers from the `illuminate/support` can also provide value, because, for example, in a Symfony there is nothing at all similar in functionality.

I can offer two solutions to this problem of extra dependencies:
1) The following code can be written in composer.json to get rid of unnecessary dependencies in the Symfony or Zend-based applications which used a Doctrine:
```json
"replace": {
    "illuminate/contracts": "*"
}
```
2) I can make this functionality optional by writing it into the `suggest` section into `composer.json`, but this breaks backward compatibility.

On the other hand, are there really a dozen extra classes that are not used — so bad?

**Comment by winkbrace** [comment]
Okay, you clearly have thought this through. :)

Thanks for the suggestions. I would never copy the `Arr` and `Str` util functions. I like the idea to replace illuminate/contracts in my symfony projects.

**Comment by SerafimArts** [comment]
> I like the idea to replace illuminate/contracts in my symfony projects.

Be careful, because some code uses `Arrayable` and `Jsonable` interfaces, in particular - Collection can throw errors if it does not provide it with these interfaces.

**Comment by SerafimArts** [comment]
P.S. If you find a more beautiful way to get rid of unnecessary dependencies and not lose functionality - u r welcome to PR =)
